### ISSUE TITLE
Support for GitHub Enterprise

### ISSUE THREAD

**Issue by ryanpsm** [Zebiano/Labeler#11]
I think this is a fantastic tool, but I can't figure out how to get it working with a GitHub Enterprise instance. Is that currently supported, or do you know an easy way to help make that happen?

**Comment by Zebiano** [comment]
Thank you for the nice feedback!
Unfortunately I do not own a GitHub enterprise account, so I can't really test this... Do you by any chance get some type of error message to point me in the right direction?

**Comment by ryanpsm** [comment]
So through the config I am able to set my username and GHE API token, but I would need a way pass in or set the host for the enterprise instance. I tried passing in the full URL to the repo and just the name itself (which I didn't expect to work), and both cases result in:

```
Error: An unexpected error occurred.
Error: Error: Request failed with status code 401
```

I was looking into this repository as well: https://github.com/popomore/github-labels
which has a little documentation for connecting to GHE instances, but that just kept giving me token errors.

For reference, using the API and curl, I can get the current list of labels for a given repo using the following command:
```
curl -u <user_name>:<token> -H "Accept: application/vnd.github.v3+json" 'https://<github.myhost.com>/api/v3/repos/<org_name>/<repo_name>/labels'
```

**Comment by Zebiano** [comment]
Thanks for that info. That does indeed help me out, especially the curl command! Would it be OK if I'd get in touch with you one day to test this feature out?

**Comment by ryanpsm** [comment]
Sure thing, I'll keep an eye on this thread, and it seems I get an email when you respond, so just let me know when you have something to test.

**Comment by Zebiano** [comment]
Alright, I think https://github.com/Zebiano/Labeler/commit/a0cafa6451c8a19465a3fa8cb684b1b1e8458bbf should add GitHub Enterprise Hosts as a feature. Could you test it out for me? In order to test it, you'd have to clone this repository, run `npm i` and run labeler with `node labeler.js [FLAGS]`.

I've added a new entry to the `labeler -c` config where you can store your custom host, or you may as well use the `-H` flag. For example:
```
node labeler.js -ur repository -H github.yourhost.com
```

Please keep in mind your token needs to have the correct permissions. I'll be waiting for your input, thank you in advance already!

**Comment by ryanpsm** [comment]
Thank you for implementing this so quickly! Running your code as is, every operation returns:
```
Error: An unexpected error occurred.
Error: Error: Request failed with status code 406
```

I took a look at your commit, and I was able to get it working by modifying lines 10 and 33 of `axios.js` to be:
```
const url = 'https://' + host + '/api/v3/repos/' + owner + '/' + repository + '/labels'
```

I'm not sure if adding the `/api/v3` will break connections to repos in standard GitHub, but if it does, we may have to either append that string to end of the host property before passing it into `getLabels` and `saveLabel`, or split the constant `url` into a logic block or ternary to decide if the string is necessary in the current execution, depending on the host.

**Comment by Zebiano** [comment]
Oh, GitHub uses different routes for the same purpose... Weird. Either way, I've pushed [a fix](https://github.com/Zebiano/Labeler/commit/ced02148f4692d30b91b826df460bf39352ecb34), I think it should work this time. If you could test it once more that would be dope! :)

**Comment by ryanpsm** [comment]
Works like a charm! Thank you for all your work on this, and I look forward to using this repo and all the headaches it will save me :)

**Comment by Zebiano** [comment]
Nice! Thank **you** though, for all the help and the testing. Makes me really happy to see people showing interest in this project! I'll play around with the code still for some other things, but expect an update for `labeler` this week at least.

Once again, thank you!

**Comment by TakosF** [comment]
nice Zeb
