### ISSUE TITLE
CTRL+V not working to paste text from Clipboard

### ISSUE THREAD

**Issue by MeerMusik** [Zebiano/Labeler#21]
Hello. Thanks for the Tool.

It seems that CTRL+V is broken. I can not paste Text I have copied to the Clipboard to 
* Enter Label Name
* Enter Label Description
* Enter Label Color

Is this a limitation of the Script or of NPM?

* Windows 10 21H1
* NPM 7.18.1
* Node 16.4.1

Thanks!

**Comment by Zebiano** [comment]
Hey there! I don't know what terminal you are using, but try copying something to your clipboard and then using the right mouse button to paste it inside the terminal, most terminals allow that.

If it still doesn't work, please tell me what terminal/editor you are using so I can try and re-create this issue myself.

**Comment by MeerMusik** [comment]
I am using the Standard Windows Command Shell.

Right, using the right Mouse Button works as usual. Sorry, totally forgot about that!

Would still be nice if using the Keyboard would work.

Thank you! Have a nice Day :)

**Comment by Zebiano** [comment]
I didn't actively code something to not let users use `Ctrl+V`, so I don't think I'd be able to change this behaviour. It's either something with the Windows Command Shell you are using, or maybe with the way [inquirer](https://www.npmjs.com/package/inquirer) handles input, but I doubt it. I'm afraid you'll have to use the right mouse button from now on in this situation.

I'm glad it worked though, have a nice day as well! :D
